### ISSUE TITLE
Make subsystem services optional (mysql, mongo, rabbitmq, memcached, smtp, elasticsearch)

### ISSUE THREAD

**Issue by lpm0073** [regisb/tutor#114]
Tutor should skip installation of any containers for subsystems that have been hived off of the default single-server configuration as part of a scaling strategy. in a perfect world your docker definitions would lookup the host names of the principal subsystems like mysql, mongo and rabbitmq from /lms/envs/common.py. in the interim however, it would be great if we could direct the installer to skip installation of containers that will not be used locally.

## Steps to reproduce

N/A

## Unexpected behavior

N/A

## Additional info (IMPORTANT)

N/A

**Comment by regisb** [comment]
This is an interesting idea! Should we also make elasticsearch optional?

**Comment by lpm0073** [comment]
yes.

**Comment by guilleironhack** [comment]
+1

**Comment by regisb** [comment]
In the next release of Tutor, external services it will be possible to enable/disable services one by one. That includes MySQL, MongoDb, Rabbitmq, SMTP server and Elasticsearch. I did not manage to setup a username/password for Memcached, so that will stay on all instances for now. I think this is an exciting feature, as it opens the possibility to distribute Tutor on multiple servers.
@lpm0073 @guilleironhack please let me know what you think!

**Comment by lpm0073** [comment]
yes, this is a very big deal. great work Régis!
