### ISSUE TITLE
local development not syncing (bind-mounting)

### ISSUE THREAD

**Issue by JeffKatzy** [regisb/tutor#134]
## Steps to reproduce

From `deploy/local`, I run `make run`

```
env | grep EDX
EDX_PLATFORM_SETTINGS=tutor.development
EDX_PLATFORM_PATH=/Users/jeff/Documents/jigsaw/software/edx-software/downloaded-edx/edx-platform
```
## Unexpected behavior

The webpage loads up fine, however it is not mounting to my local repo of edx.
I tested this by changing the edx homepage locally, then viewed code inside of container repo, and code was unchanged.

Also did not see code mounted when running `docker inspect local_lms_1`.

I tried debugging by adding changing makefile to: 

```
run: 
  docker-compose up 
  @echo "Platform path is $(EDX_PLATFORM_PATH) with settings of $(EDX_PLATFORM_SETTINGS)"  

```

but did not see this line after searching through terminal

Any ideas?

## Additional info (IMPORTANT)
```
/Library/Developer/CommandLineTools/usr/bin/make -s -C ../.. info
Darwin Jeffreys-MacBook-Air.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
-------------------------
c9314e196d66c1275d936e20dc44a65510506962
-------------------------
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
-------------------------
docker-compose version 1.23.2, build 1110ad01
-------------------------
/Users/jeff/Documents/jigsaw/software/edx-software/downloaded-edx/edx-platform
tutor.development
```

**Comment by regisb** [comment]
Hi @JeffKatzy! It is not possible to mount your edx-platform repo this way. You have two choices:

1. Run `make lms` or `make lms-runserver` instead of `make run`, as described [in the docs](http://docs.tutor.overhang.io/en/latest/dev.html). Basically, these commands run a command similar to `docker-compose run --volume=... lms`.
2. Re-build the openedx docker image to use your fork, as per [the docs](http://docs.tutor.overhang.io/en/latest/customise.html#forked-version-of-edx-platform). But this is not well suited to rapid iteration with a local edx-platform folder.

The reason why it's not possible to do what you want, is that we may not write the docker-compose.yml to conditionally mount a folder. We can't write:

```
lms:
    volumes:
        if EDX_PLATFORM_PATH is defined:
        ${EDX_PLATFORM_PATH}:/openedx/edx-platform
        endif
```

I'm going to close this. Feel free to re-open or comment if you feel your problem was not solved.
