### ISSUE TITLE
Starting local_mysql takes forever

### ISSUE THREAD

**Issue by kbitr** [regisb/tutor#136]
## Steps to reproduce

Have an older version of tutor. git pull. make all. wait.

## Unexpected behavior

```docker-compose up -d mysql
Starting local_mysql_1_3aca34de5483 ... done
until docker-compose logs mysql | grep "MySQL init process done. Ready for start up."; do \
        sleep 1;\
done
```
takes forever

## Additional info (IMPORTANT)

Related to commit: c42b747e3538eb8f0ead1534c381933afdc0b87e

## intermediate solution

just don't wait - I assume this happens, because one is not supposed to run make all again, once everything is up?

**Comment by regisb** [comment]
Hi @kbitr! Waiting for mysql to be ready is key, and prior to introducing this change there were many  bugs that were difficult to solve. E.g: #3, #75, #120.
The problem is that on the first boot, mysql needs to initialize the root user with the right password. If it doesn't, databases cannot be created and migrations do not run. Basically, it's a race condition problem.

To better understand your problem, please answer the following questions:

1. What does it mean when you say "forever"? Is it just a long time, or do you mean that the command never ends?
2. If the command ends, how long does it take? (approximately)
3. If the command does not end, what is the full output of `docker-compole logs mysql`?

**Comment by kbitr** [comment]
Hey, I have to do this on my production server, so I did not wait long this time to have no downtime. But since the output is the following, I assume that nothing will happen anyway.
```
2019-01-27 13:09:20 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2019-01-27 13:09:20 0 [Note] mysqld (mysqld 5.6.36) starting as process 1 ...
```

**Comment by regisb** [comment]
@kbitr you're right: the message is not printed once the mysql db has already been initialized. I just commited a fix. Please confirm that it works for you, as usual :)
