### ISSUE TITLE
Docker Entrypoint file location

### ISSUE THREAD

**Issue by nikhilrayaprolu** [regisb/tutor#144]
## Additional info (IMPORTANT)

https://github.com/regisb/tutor/blob/master/build/openedx/Dockerfile#L93

I couldn't find the docker-entrypoint.sh anywhere?

**Comment by regisb** [comment]
Hi @nikhilrayaprolu! Since you solved your initial question, I'm going to close this, if you don't mind.

>  Also how about caching in tutor? Is caching being handled?

What kind of caching are you talking about? Docker layer caching? 

> I am planning to use kubernetes for CD pipeline for openedx, I believe the present state of tutor supports building such a pipeline, let me know your inputs. If I could build the CD pipeline, I am planning to write a blog on that.

This is awesome, although I'm note quite sure what "CD" stands for :) Continuous delivery? Anyway, please let me know when you publish your blog article!
