### ISSUE TITLE
How to redirect multiple subdomains to LMS

### ISSUE THREAD

**Issue by nikhilrayaprolu** [regisb/tutor#170]
Presently tutor supports only one subdomain `preview.youngsphere.com`, but OpenedX supports multitenancy, what are the required changes on the nginx configuration to allow tutor based edx servers to accept multiple subdomains.

**Comment by nikhilrayaprolu** [comment]
I figured it out, though I am not sure whether this is the right practice:

1. I appended "*" into ALLOWED_HOSTS for lms settings
2. Then changed the server_name in https://github.com/regisb/tutor/blob/master/tutor/templates/apps/nginx/lms.conf to {{ LMS_HOST }}  ~^(www\.)?(?P<domain>.+)\.{{ LMS_HOST }}

**Comment by regisb** [comment]
Hi @nikhilrayaprolu! I'm going to be frank: I think multi-tenancy in Open edX is a terrible feature. It makes the code base extremely complicated, not to mention deployment issues. For instance, if we want to support multi tenancy in Tutor, we need to generate multiple HTTPS certificates (one for each domain). Settings need to be modified, too. I'm not too sure what we are supposed to do to support multi tenancy because this feature is poorly documented. I only found this page on the old wiki: https://github.com/edx/edx-platform/wiki/Microsites-Theming (last updated 4 years ago).
IMHO, multi tenancy was introduced in Open edX because it was both very complicated and costly to run multiple Open edX instances on the same server. But with Tutor, it becomes relatively easy to run multiple Open edX instances side to side on the same server. That makes multi-tenancy unnecessary.
So I'm going to close this issue as an unsupported feature. However, I'm ready to change my mind: you can try to convince me by describing your

**Comment by Naren-Kallakuri** [comment]
@regisb , is the database same or different for multiple Open edX instances on same server?
We are looking at multiple sites with same storage as we don't want to duplicate the data and have same users be able to access the different sites. So is there a way we can achieve that with tutor?

**Comment by regisb** [comment]
@Naren-Kallakuri Please don't ask questions on Github issues: https://docs.tutor.overhang.io/troubleshooting.html

> is the database same or different for multiple Open edX instances on same server?

Different.

>  We are looking at multiple sites with same storage as we don't want to duplicate the data and have same users be able to access the different sites. So is there a way we can achieve that with tutor?

I have no idea, and as I mentioned earlier I think this is a terrible idea.
