### ISSUE TITLE
tutor dev runserver lms --edx-platform-path=/path/to/edx-platform error

### ISSUE THREAD

**Issue by nikhilrayaprolu** [regisb/tutor#173]
## Steps to reproduce

When we run `tutor dev runserver lms`, it works perfectly
but when we run `tutor dev runserver lms --edx-platform-path=/path/to/edx-platform` , it fails as the entry_points in the setup.py file are not available.

![image](https://user-images.githubusercontent.com/15216503/52912039-e438eb80-32d1-11e9-97ca-737a9eb5879a.png)

## How I fixed it
instead of running `tutor dev runserver lms --edx-platform-path=/path/to/edx-platform` I ran 
`tutor local run lms--edx-platform-path=/path/to/edx-platform /bin/bash`  which brought me to the terminal,
then I ran `python setup.py install` 
and then `python manage.py  lms runserver --settings=tutor.development 0.0.0.0:8000`

But I am not sure, why python setup.py install is required for `tutor dev` but not for `tutor local`

**Comment by regisb** [comment]
@nikhilrayaprolu Indeed, it is necessary to run `python setup.py` on your own repo before you can run `runserver`. This is because compilation files are generated inside your edx-platform repo. In a nutshell, run:

    tutor dev run --edx-platform-path /path/to/edx-platform lms python setup.py install

And then:

    tutor dev runserver lms --edx-platform-path  /path/to/edx-platform

It's not a bug, it's a feature ;) But the documentation should certainly be improved to give more precise instructions.

**Comment by nikhilrayaprolu** [comment]
@regisb Thanks a lot for the clarification :)
