### ISSUE TITLE
Copying data between machines, etc. 

### ISSUE THREAD

**Issue by travlr** [regisb/tutor#188]
Purpose: Using data between machines.. in this case "staging" and "dev".

## Steps to reproduce

__**STAGING SERVER**__

tutor version: 3.2.1

1. `tutor local stop`
2. `tar cvf backup.tgz $(tutor config printroot)/config.yml $(tutor config printroot)/data`

__**DEV SERVER**__

tutor version: 3.3.1

1. `tutor local stop`
2. scp tarball from staging server
3. `tar xvf backup.tgz -C $(tutor config printroot)/`
4. `tutor local quickstart --pullimages` (produces error.. see attached image)

## Unexpected behavior

![staging-to-dev-server_data-error](https://user-images.githubusercontent.com/125945/55103694-952f6480-508e-11e9-97f5-3c2c5d7a729f.png)

## Additional info (IMPORTANT)

tutor versions listed above

**Comment by regisb** [comment]
Hi @travlr! Sorry for answering so late, I was on holiday and then this issue flew under my radar when I came back.
I face a couple issues when I try to reproduce this: first, I need to run the compress command (`tar cvf`) with `sudo` in order to read rabbitmq and mysql data. Then, the decompressed folder has an incorrect structure. Can you please paste here the contents of the tutor root project on the staging server, after the backup is restored?

    ls -l $(tutor config printroot)
    ls -l $(tutor config printroot)/env
    ls -l $(tutor config printroot)/data

**Comment by travlr** [comment]
@regisb .. Hi Regis :) No worries I knew you were on holiday and I've been putting out other fires, so there was no rush.. but, I sincerely thank you for your consideration.  

I've sent you an email, as I've meant to do since we first engaged. Regarding this Issue.. thank you, I'll get back to this today and provide that additional information you need. Thanks :)

**Comment by travlr** [comment]
> I face a couple issues when I try to reproduce this: first, I need to run the compress command (tar cvf) with sudo in order to read rabbitmq and mysql data.
> Then, the decompressed folder has an incorrect structure.

My mistakes Regis. Yes, sudo is needed and the problem with the tarball was because `$(tutor config printroot)` is an absolute file path. It shoud be..
`cd $(tutor config printroot) && tar cvf backup.tgz $(tutor config ./config.yml ./data`. 

So at this point, I have done the procedure I've described above. Then, copied all passwords, keys and id over from the original config.yml that I backed up before the procedure. I then ran `tutor local stop && tutor local databases` and got the error. I'm wondering about `tutor config save` in this case.. I'll get a better understanding of "config save" tomorrow.

Lastly, this is now a transfer from Hawthorn.1 to Ironwood.1 servers.

I have the error attached below. 

I thought I'd just post this up here now in case you can point me in the right direction quicker than when I dive into the issue further tomorrow. ~Peter

[error-moving-databases.txt](https://github.com/regisb/tutor/files/3109312/error-moving-databases.txt)

**Comment by regisb** [comment]
>  `cd $(tutor config printroot) && tar cvf backup.tgz $(tutor config ./config.yml ./data`

@travlr I'm confused by this command, which does not seem valid. Could you please double-check? It's important for me to have the exact command you are running in order to reproduce. The error is probably caused by a seemingly innocuous manipulation.

> I'm wondering about tutor config save in this case

`tutor config save` does two things:
- generate the `config.yml` file: during the migration, this will add any missing parameter and migrate obsolete parameters.
- generate the `env` folder: environment files have changed between hawthorn and ironwood, so they need to be updated.

> error-moving-databases.txt

This file contains your database password (from your production server, right?), so I took the liberty to remove it from your post. Let's just remember that the error is `django.db.utils.OperationalError: (1045, "Access denied for user 'openedx'@'172.18.0.9' (using password: YES)"` during LMS migrations. These migrations should work because the root user was correctly created during database creation.

**Comment by travlr** [comment]
Hi Regis.. damn it, I'm sorry about that.. again :-P . `cd $(tutor config printroot) && tar cvf backup.tgz ./config.yml ./data`. 

I'm working on this now.. I'll will report as soon as I've made progress.. thank you

**Comment by travlr** [comment]
Sorry for having left this issue open for so long.. I am going to close it now and re-address the issue again down the road, as it seems to work with one exception of the forum's db re-indexing. This doesn't seem to affect my build as I've disabled search functionality and haven't been concerned with the forums yet.
